%% manipulate indiv clusters to remove A1 or only keep it
% J Boyer November 2025 - SoundfMRI
% idea = re-doing the RFE svm on those ROIs and then extract single trial
% activity from the RFE-selected voxels + looking at decoding perf of
% snr5 vs 1 specifically in A1 and in the rest of the activations

% so the ROIs we want, for each sibject:
% - all cluster MINUS A1
% - only AI intersecting cluster

%% after re looking (26/01/26)
% brainnetome atlas is not specific enough --> Harvard Oxford for Heschl
% gyrus ++

%% Main Methods text (recommended)
% Anatomically constrained ROIs
% 
% Anatomical regions of interest (ROIs) corresponding to primary auditory 
% cortex were defined using the Harvard–Oxford probabilistic cortical atlas
% distributed with FSL. Bilateral Heschl’s gyrus probability maps were used
% as an anatomical proxy for primary auditory cortex. Probabilistic atlas 
% maps were resliced to each subject’s functional space (2.5 mm isotropic 
% voxels) using trilinear interpolation in SPM12 to ensure voxelwise 
% correspondence with subject-specific activation maps. The resliced 
% probabilistic maps were then thresholded at XX% probability and 
% binarized to generate anatomically constrained ROI masks.
% 
% Subject-specific activation clusters were intersected with the binarized
% Heschl’s gyrus masks to obtain ROIs corresponding to cluster voxels located 
% within primary auditory cortex (“A1 ROI”). Complementary ROIs excluding 
% primary auditory cortex were generated by subtracting the Heschl’s gyrus 
% mask from the activation clusters (“non-A1 ROI”). All ROIs were defined in 
% individual functional space and used for subsequent multivariate and
% signal-extraction analyses.

% A probability threshold of 25(XX)% was chosen to balance anatomical 
% specificity and inter-individual variability in Heschl%s gyrus morphology.

% Slightly more technical version (if reviewers in your field expect it)
% The Harvard–Oxford probabilistic atlas provides voxelwise probabilities 
% (0–100%) reflecting the proportion of subjects in whom each voxel belongs
% to a given anatomical label. To avoid inclusion of low-confidence voxels, 
% probabilistic maps were thresholded at 25% prior to binarization. 
% Reslicing was performed from MNI space to subject-specific functional 
% space using trilinear interpolation, resulting in anatomically constrained
% ROIs matched to the spatial resolution of the functional data.

%% setup 
clc; clear; close all; 
addpath('/Applications/spm12/');
temp = spm_vol('/Volumes/DisqueJulie/JulieBoyer2025/SOUNDFMRI 2025/ACTIVE/Scans/SOUNDFMRI_SUJET02_ACTIVE/wts_OC_run0.nii');
ref_img = temp(1);

input_dir = '/Volumes/DisqueJulie/JulieBoyer2025/SOUNDFMRI 2025/Unsmoothed_indivGLMsingle_modelC/Oct25/indivClusters/';
main_dir = '/Volumes/DisqueJulie/JulieBoyer2025/SOUNDFMRI 2025/MVPA/withTDT/new_codes/FirstLevel/ROI/snr/new_ROIs_2/';

subjects = [2 3 4 5 6 7 8 9 10 12 13 14 15 18 19 20 21 22 23 24 25 26 27 28 29 30 32];
conditions = {'active','passive'};

dirz = '/Volumes/DisqueJulie/JulieBoyer2025/SOUNDFMRI 2025/MVPA/withTDT/new_codes/FirstLevel/ROI/snr/atlas_for_rois/';

threshold = 50; %10 / 25 / 50
correction = 'unc001'; %'FWE05'; 

%% get the atlas ROI (not thresholded)

Va1 = spm_vol([dirz 'HO_Heschl_bilat_noThres.nii']);
A1 = spm_read_vols(Va1);

% put it into functional scans' space

%% reslice Harvard–Oxford atlas into subject space (cluster space)

reslice_flags = struct( ...
    'interp', 1, ...      % trilinear (OK for probabilistic atlas)
    'wrap',   [0 0 0], ...
    'mask',   0, ...
    'which',  1, ...      % reslice source only
    'mean',   0);
V = ref_img;
spm_reslice({V.fname, Va1.fname}, reslice_flags);

% load resliced atlas
[atlas_path, atlas_name, atlas_ext] = fileparts(Va1.fname);
Va1_r = spm_vol(fullfile(atlas_path, ['r' atlas_name atlas_ext]));
A1_r  = spm_read_vols(Va1_r);

clear V;
% threshold it 

%% main loop to get indiv ROIs
for isubj = subjects % loop across subjects

    for icond = 1:numel(conditions) % loop across conditions
        active = false; passive = false;
        if strcmp(conditions{icond},'active')
            active = true; 
        elseif strcmp(conditions{icond},'passive')
            passive = true; 
        end
        % define input / output directories
        input = [input_dir 'subj' num2str(isubj) '/'];
        output1 = [main_dir correction '/HO_thr' num2str(threshold) '/noA1/subj' num2str(isubj) '/'];
        output2 = [main_dir correction '/HO_thr' num2str(threshold) '/onlyA1/subj' num2str(isubj) '/'];

        if ~isfolder(output1)
            mkdir(output1);
        end
        if ~isfolder(output2)
            mkdir(output2);
        end
        
        % load & read cluster activation map
        if active
            %volz = ([input 'CApmodSNR_spmT_thr_FWE05.nii']);
            volz = ([input 'CApmodSNR_spmT_thr_unc001.nii']);
        elseif passive
            %volz = ([input 'CPpmodSNR_spmT_thr_FWE05.nii']);
            volz = ([input 'CPpmodSNR_spmT_thr_unc001.nii']);
        end
        V = spm_vol(volz);
        Y = spm_read_vols(V); 
        %fullcluster_idx = Y>1;

        % do the modifs 
        %% added = threshold if HO atlas

        % ALSO: put all back into the same space !! 
        % for now: fullcluster_idx = 69x83x68 / A1 = 182x218x182 ++
        % probabilistic atlas so must be thresholded! (0 - 100)
        %% threshold probabilistic HO atlas (Heschl)

        A1_mask = A1_r >= threshold;   % binary mask

        % A1_cluster_mask = fullcluster_idx; A1_cluster_mask(A1_mask == 0) = 0;
        % noA1_cluster_mask = fullcluster_idx; noA1_cluster_mask(A1_mask == 1) = 0;


        % activation cluster (already binary)
        fullcluster_idx = Y > 1;

        % ONLY A1 ∩ cluster
        A1_cluster_mask = fullcluster_idx & A1_mask;

        % cluster MINUS A1
        noA1_cluster_mask = fullcluster_idx & ~A1_mask;

        % save .nii
        % noA1
        c = ref_img;
        c.fname = [output1 conditions{icond} '.nii'];
        d = noA1_cluster_mask;
        spm_write_vol(c,d);

        % onlyA1
        c = ref_img;
        c.fname = [output2 conditions{icond} '.nii'];
        d = A1_cluster_mask;
        spm_write_vol(c,d);

    end
end
